---

- name: apt | Install openvpn requirements
  apt: name={{item}} update_cache=yes
  with_items:
    - openvpn
    - udev
    - openssl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: apt | make openvpn autostart
  replace: dest=/etc/default/openvpn regexp="^#AUTOSTART=\"all\"" replace="AUTOSTART=\"all\""
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install openvpn requirements
  yum: name={{item}}
  with_items:
    - openvpn
    - udev
    - openssl
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Redhat | Ensure services are enabled on boot.
  service: name=openvpn enabled=yes
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Alpine | Install openvpn requirements
  apk: name={{item}}
  with_items:
    - openvpn
    - udev
    - openssl
  when: ansible_os_family == "Alpine"
- name: map local config to {{ openvpnclient_confdir }}/openvpn.conf
  file: "src={{ openvpnclient_confdir }}/{{ inventory_hostname }}.conf dest={{ openvpnclient_confdir }}/openvpn.conf mode=0644 state=link force=yes"
  ignore_errors: true
  when: ansible_os_family == "Alpine"

- include: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: push configuration
  copy: "src={{ item }} dest={{ openvpnclient_confdir }}/ mode=0400"
  with_items: openvpn_config_files
  notify:
    - restart openvpn
    - restart openvpn synology
    - openvpn restart - darwin
  when: openvpn_config_files is defined

- name: push keys
  copy: "src={{ item }} dest={{ openvpnclient_confdir }}/keys/ mode=0400"
  with_items: openvpn_config_keys
  notify:
    - restart openvpn
    - restart openvpn synology
    - openvpn restart - darwin
  when: openvpn_config_keys is defined

- name: Create config for login/pass authenticated users
  template: "src=openvpn-user.ovpn dest={{ openvpnclient_confdir }}/openvpn-{{ item.u }}.{{ openvpnclient_ext }} mode=0400"
  with_items: openvpn_config_users
  notify:
    - restart openvpn
    - restart openvpn synology
    - openvpn restart - darwin
  when: openvpn_config_users is defined

- blockinfile:
    dest: "{{ openvpnclient_confdir }}/keys/login-{{ item.u }}.txt"
    mode: 0400
    create: yes
#    marker: ''
    block: |
      {{ item.u }}
      {{ item.p }}
  with_items: openvpn_config_users
  notify:
    - restart openvpn
    - restart openvpn synology
    - openvpn restart - darwin
  when: openvpn_config_users is defined

## http://fedoraproject.org/wiki/Openvpn
- stat: path='/lib/systemd/system/openvpn@.service'
  register: systemd
- name: symlink starting config - systemd only
  file: src='/lib/systemd/system/openvpn@.service' dest="/etc/systemd/system/openvpn@{{ inventory_hostname }}.service" state=link
  when: systemd.stat.exists
  register: out
- debug: var=out

- name: Ensure services are enabled and started
  service: name=openvpn enabled=yes state=started

